name: Build and deploy Node.js, React, and Panel apps to Azure Web App - peppapigproyectcrm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step for api_node
      - name: npm install for api_node
        run: |
          cd api_node
          npm install

      - name: npm build for api_node
        run: |
          cd api_node
          npm run build --if-present

      - name: npm test for api_node
        run: |
          cd api_node
          npm run test --if-present

      # Step for React client
      - name: npm install for client
        run: |
          cd client
          npm install

      - name: npm build for client
        run: |
          cd client
          npm run build

      # Step for panel
      - name: npm install for panel
        run: |
          cd panel
          npm install

      - name: npm build for panel
        run: |
          cd panel
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd api_node
          zip -r ../release.zip .
          cd ../client/build
          zip -ur ../../release.zip .
          cd ../../panel/build
          zip -ur ../../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9E2A7B7C830B41F59B4198734C41B38B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_602E266451F74EB9BF4D7B78DCD275C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C27B5EC4ADFA497EBD0E5C4399E5CB11 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'peppapigproyectcrm'
          slot-name: 'Production'
          package: .
